/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package awp_mysql2;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 *
 * @author Admin
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        check = new javax.swing.JTextField();
        remove = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        display = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ADMIN");

        jButton1.setText("REMOVE USERS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("CHECK ENTRIES OF USER");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("DISPLAY ALL USERS");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        display.setColumns(20);
        display.setRows(5);
        jScrollPane1.setViewportView(display);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(check, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(remove, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(192, 192, 192))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(302, 302, 302)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(230, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(remove, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(check))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String username =remove.getText();
        
        
        try{  
                                    Class.forName("com.mysql.jdbc.Driver");  
                                    Connection con=DriverManager.getConnection(  
                                    "jdbc:mysql://localhost:3306/awp","root","");  
                                    //here sonoo is database name, root is username and password  
                                    Statement stmt=con.createStatement(); 
                                    //String sql ="INSERT INTO `logs2`(`Username`, `Utility`) VALUES ("+"\""+username+"\""+","+received+")";
                                    String sql ="DELETE FROM `users` WHERE `userame` ="+"\""+username+"\"" ;
//                                    PreparedStatement preparedStmt = con.prepareStatement(sql);
//                                    preparedStmt.setString(1,"u");
//                                    preparedStmt.setString(2,"s");
                                    int executeUpdate = stmt.executeUpdate(sql);  
                                    //int rs= preparedStmt.executeUpdate();
                                    //int rs=stmt.executeUpdate(sql); 
                                    remove.setText("");
                                    con.close();  
                                    }
                                catch(Exception e)
                                { 
                                    System.out.println(e);
                                }  
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try{  
                                    Class.forName("com.mysql.jdbc.Driver");  
                                    Connection con=DriverManager.getConnection(  
                                    "jdbc:mysql://localhost:3306/awp","root","");  
                                    //here sonoo is database name, root is username and password  
                                    Statement stmt=con.createStatement(); 
                                    //String sql ="INSERT INTO `logs2`(`Username`, `Utility`) VALUES ("+"\""+username+"\""+","+received+")";
                                    String sql = "SELECT DISTINCT `userame`, `password` FROM `users` WHERE 1";
//                                    PreparedStatement preparedStmt = con.prepareStatement(sql);
//                                    preparedStmt.setString(1,"u");
//                                    preparedStmt.setString(2,"s");
//                                    int executeUpdate = stmt.executeUpdate(sql);  
                                    //int rs= preparedStmt.executeUpdate();
                                    //int rs=stmt.executeUpdate(sql);  
                                    ResultSet rs=stmt.executeQuery(sql);  
                                    int count =0;
                                    while(rs.next())  
                                    {
                                        if(count ==0)
                                        {
                                            display.setText("USERNAME"+"    "+"PASSWORD"+"\n");
                                            count++;
                                        }
                                       display.setText(display.getText()+rs.getString(1)+"    "+rs.getString(2)+"\n"); 
                                    }
                                    con.close();  
                                    }
                                catch(Exception e)
                                { 
                                    System.out.println(e);
                                }  
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String ut =check.getText();
        
        try{  
                                    Class.forName("com.mysql.jdbc.Driver");  
                                    Connection con=DriverManager.getConnection(  
                                    "jdbc:mysql://localhost:3306/awp","root","");  
                                    //here sonoo is database name, root is username and password  
                                    Statement stmt=con.createStatement(); 
                                    //String sql ="INSERT INTO `logs2`(`Username`, `Utility`) VALUES ("+"\""+username+"\""+","+received+")";
                                    String sql = "SELECT `Username`, `Utility` FROM `logs2` WHERE `username`="+"\""+ut+"\"";
//                                    PreparedStatement preparedStmt = con.prepareStatement(sql);
//                                    preparedStmt.setString(1,"u");
//                                    preparedStmt.setString(2,"s");
                                   ResultSet rs=stmt.executeQuery(sql);  
                                    int count =0;
                                    while(rs.next())  
                                    {
                                        if(count ==0)
                                        {
                                            display.setText("USERNAME"+"    "+"UTILITY"+"\n");
                                            count++;
                                        }
                                       display.setText(display.getText()+rs.getString(1)+"       "+rs.getString(2)+"\n"); 
                                    }
                                    check.setText("");
                                    con.close();  
                                    }
                                catch(Exception e)
                                { 
                                    System.out.println(e);
                                }  
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField check;
    private javax.swing.JTextArea display;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField remove;
    // End of variables declaration//GEN-END:variables
}
